### ISSUE TITLE
still a problem since 10.5 and plugin version 5

### ISSUE THREAD

**Issue by bwaddington** [jellyfin/jellyfin-plugin-tmdbboxsets#14]
Server: Jellyfin
Version: 10.5.2
Operating System: Linux
Architecture: X64

i have tried total uninstall of tmdbboxsets and removal of collections and reinstall still the same.
this didnt happen on 10.4 not sure what has changed

it seem to find all the collections but in some there not right 

like this 1 is right and 1 is wrong 
![1](https://user-images.githubusercontent.com/30188767/78466797-c7da5700-76fd-11ea-8a88-95717d9ae269.jpg)

1 leads to this wrong
![2](https://user-images.githubusercontent.com/30188767/78466820-f0fae780-76fd-11ea-8844-a57dae05dd0a.jpg)

1 leads to this right
![3](https://user-images.githubusercontent.com/30188767/78466832-040db780-76fe-11ea-9ef1-62a5f04331df.jpg)

same agen but 2 is right and 2 is wrong 
![4](https://user-images.githubusercontent.com/30188767/78466855-30293880-76fe-11ea-8d86-17f28c634394.jpg)

same agen 2 leads to like this wrong 
![5](https://user-images.githubusercontent.com/30188767/78466867-5a7af600-76fe-11ea-8631-3defd74c534c.jpg)

and same agen 2 leads to this right
![6](https://user-images.githubusercontent.com/30188767/78466878-826a5980-76fe-11ea-8041-239e87097a07.jpg)

thank you for any help and thank you for all the work

**Comment by bwaddington** [comment]
bug

**Comment by Webbeh** [comment]
I have the same issue.
Tried a clean install of the plugin and a full rescan of the library.

All the movie files were identified properly in the Movies library, but some of them don't retain their names when scanned in a collection.

Moreover, it is not possible to identify those files from the Collection (the Identify option disappeared from the context menu).

In "Movies" :
![image](https://user-images.githubusercontent.com/1530837/79067487-e1603d80-7cbf-11ea-9fc6-5676ba21eae2.png)

In "Collections" : 
![image](https://user-images.githubusercontent.com/1530837/79067492-f50ba400-7cbf-11ea-9e26-8707117485c1.png)

Context menu : 
![image](https://user-images.githubusercontent.com/1530837/79067499-fe950c00-7cbf-11ea-89d8-6d4e4b4f666c.png)

**Comment by lafricote** [comment]
Jellyfin 10.5 ,10.5.5 = collections crash

**Comment by crobibero** [comment]
> 
> 
> Jellyfin 10.5 ,10.5.5 = collections crash

Please create a enw

**Comment by mcarlton00** [comment]
The metadata/missing posters are a bug in Jellyfin proper, not the boxsets plugin.  It's been fixed in master and will be released in 10.6

See https://github.com/jellyfin/jellyfin/issues/2565
