### ISSUE TITLE
Plugin options save button has wrong text

### ISSUE THREAD

**Issue by unikitty37** [jellyfin/jellyfin-plugin-tmdbboxsets#36]
The save button text is showing as `ButtonSave` for me.

My browser is passing `Accept-Language: en-GB,en;q=0.5` in the request.

From https://github.com/jellyfin/jellyfin-web/pull/1796, it looks like `ButtonSave` might need to be changed to `Save`.

**Comment by anthonylavado** [comment]
It's an issue with translations, we're aware of it, but it can't be easily corrected until the next major version.
