### ISSUE TITLE
Is it possible to show Collection under movie details if movie is part of Collection?

### ISSUE THREAD

**Issue by hugalafutro** [jellyfin/jellyfin-plugin-tmdbboxsets#45]
Hi,
there's  movies that are not called movie 1, movie 2, movie part 3 etc so sometimes I watch a movie and then later I discover in Collections that it was actually 2nd movie of 3 etc. 

Would it be possible to display corresponding Collection under movie info? I.e. I click on a movie that is part of a Box Set, it will show it's usual metadata info, media info, scenes etc. then under that it would show something like "Part of the XXXX collection" with the XXXX being button/picture of the collection".

Hope that makes sense.

**Comment by cvium** [comment]
That is a feature request for the (web) clients. This plugin is only about creating the collections.
