### ISSUE TITLE
Some questions about collection handling

### ISSUE THREAD

**Issue by Shadowghost** [jellyfin/jellyfin-plugin-tmdbboxsets#5]
Thanks for this great plugin! Way better than creating every collection by hand.
While using it I was courious if some behaviour is intended and if it may be possible to alter it:
- When searching, no collections are shown in the results (seems like they are excluded from search) - is this intentional?
- Every collection has _**Collection**_ added to the end of its title. This is kind of redundant because collections are only listed in the _Collections_ tab anyway. Is it possible to make this behaviour configurable or just to not add the term to every title?

Thanks for your work!

**Comment by anthonylavado** [comment]
I can only answer about the naming. The collections aren’t necessarily *just* in the collections tab. You can also turn on a setting that mixes it in with the regular Movies library.

I’m sure it could probably be made configurable,  but someone will have to add that function in.

**Comment by danimart1991** [comment]
Hi @Shadowghost 

- What hidden collections are you mentioning about? 🤔
- There is an option to remove the Collection part from the name.

**Comment by cvium** [comment]
>     * What hidden collections are you mentioning about? 🤔

Using the search bar you can't find collections.

>     * There is an option to remove the Collection part from the name.

`Collection` is translated in TMDb. There is only an option to remove the English variant.

**Comment by danimart1991** [comment]
Hi @cvium.

The first one it's not related with the plugin, must be issued in Jellyfin repository. For the second one there is a Pull Request waiting. 😊
