### ISSUE TITLE
MCU is Split into Mini Collections Instead of a Single Comprehesive Collection

### ISSUE THREAD

**Issue by RedSoxFan04** [jellyfin/jellyfin-plugin-tmdbboxsets#53]
I'd really like to be able to have a single collection for my MCU movies instead of having them split up into mini-collections. If you have more than one series of MCU movies (i.e. Iron Man, Captain America, Thor), it will group them together. That's fine if you only have a few MCU movies and they're all from the same mini-series (i.e. Iron Man 1-3), but what if you have all of the MCU movies? Why can't they all be in a single large collection instead of being split off into mini-franchises? Or at least, why can't there be an option to do it one way or the other?

**Comment by cvium** [comment]
TMDb only returns 1 collection from this endpoint https://developers.themoviedb.org/3/movies/get-movie-details
