### ISSUE TITLE
Not compatible with recent 10.8 builds/nightly builds

### ISSUE THREAD

**Issue by GermanCoding** [jellyfin/jellyfin-plugin-tmdbboxsets#66]
PR https://github.com/jellyfin/jellyfin/pull/7321 in jellyfin server project changed method

[MediaBrowser.Model/Tasks/IScheduledTask.cs](https://github.com/jellyfin/jellyfin/pull/7321/files#diff-195f93576d3651ec3677524bd6602524668fd2869d92f141d01603b91238f97e) :: Execute to ExecuteAsync, which broke this plugin (among others). Plugin does not load anymore due to this change.

**Comment by crobibero** [comment]
Plugins do not target unstable. This will be resolved with the next release of Jellyfin.

**Comment by GermanCoding** [comment]
10.8 is now in beta, yet this issue still exist. What's the policy here? Because the releases page states this plugin "supports 10.8", which it does not. Is this issue still invalid?

**Comment by crobibero** [comment]
Give me some time to update the plugins. The beta was created about 1 hour ago.
