### ISSUE TITLE
TMDb Boxset for Linux

### ISSUE THREAD

**Issue by chp-1960** [jellyfin/jellyfin-plugin-tmdbboxsets#88]
Hi,
Sorry to post here but I can't find the right place for this request.
Until now, I used Jellyfin Server on Windows but lately I moved to Linux and Jellyfin Server followed that.
But I was surprised to see the TMDb Boxset plugin was not present for Debian/Ubuntu or Linux.

So, my question / request is the following : is it planned to provide this plugin for Linux ?

**Comment by crobibero** [comment]
Not sure what you mean, plugin availability has nothing to do with operating system. I use the plugin on my Debian server.

**Comment by chp-1960** [comment]
Ok, sorry I had to be more precise. I'm really a noob on Linux and made the move recently from windows to Mint 22 (24.04 LTS) and many aspects are still obscure for me.

I finally managed to install Jellyfin server and when I had to configure / add some plugins, I saw TMDb Boxset plugin was not available  in the plugin catalog. So, I headed to the Github repository for this plugin and in the download section there is only .dll files (which mean it's for Windows) and nothing for Linux. The main page say nothing about Linux.

If it exist for Linux, I'll be pleased to know how to install it. I learned the plugin folder should be '/var/lib/jellyfin/plugins/' I don't know what to do.

**Comment by crobibero** [comment]
.dll files are the extension that dotnet compiles to, it is not windows specific.

**Comment by chp-1960** [comment]
Ah. Ok. If I uderstand well, the .dll file need to be compiled with .net to match my specific Jellyfin server version ?

Never done that before but I can try if someone can explain me what are prerequisites and how to do it (step by step). That's a big difference with the Windows version where everything was included into the Jellyfin server package.

I'm not a developer. Just an user so, if it's the case,  it's not easy for me to understand things still need to be "compiled" prior to use it. Or I missed something ?

**Comment by nielsvanvelzen** [comment]
You don't need to manually copy the dll file, just install via the Jellyfin dashboard.

Make sure you have the stable plugin repository configured (`https://repo.jellyfin.org/files/plugin/manifest.json`), then the TMDb Box Sets plugin is at the bottom of the page (doesn't have a picture).
