### ISSUE TITLE
Hide Collections Library from Home

### ISSUE THREAD

**Issue by philosen** [jellyfin/jellyfin-plugin-tmdbboxsets#9]
Right now I don't want to use the plugin as I don't want a separate collections library showing up between my other libraries. Would be nice to have an option to hide the collections library.

**Comment by anthonylavado** [comment]
This is an option, actually.
Open the Web interface, and click on the "person" icon at the top right. From the list of options, choose "Home". Scroll down until you see the heading for Collections. There's a check box you can turn off, called "Display on home screen".
🙂

**Comment by philosen** [comment]
Ok, now I feel a bit silly 😅 I thought I checked all the options. Only started using Jellyfin a couple of days ago though..

**Comment by anthonylavado** [comment]
No worries! We know it’s not so easy to find. We’re working on that :-)

**Comment by Ulrar** [comment]
Hi,

I've unticked "Display in home screen sections such as latest media and continue watching" which is the only box under the collections heading, but that doesn't seem to do anything, collection is still under My Media on the home screen.
Did that change with 10.7 ?

**Comment by anthonylavado** [comment]
@Ulrar Sorry for the really delayed response. I just checked this on my own main server and a test server. The option is still the same, it still works, and the text should be the same.

Ignoring the theme, this is what I have:
![collections](https://user-images.githubusercontent.com/596194/113496390-24b24e00-94c7-11eb-87aa-9bdfd06b0b61.png)

**Comment by Ulrar** [comment]
Hi, no worries.

It seems different, this is what I have :

![image](https://user-images.githubusercontent.com/873423/113501978-1264fe00-9521-11eb-95e4-14a0bae319f1.png)

And yet it still shows on the main screen : 

![image](https://user-images.githubusercontent.com/873423/113501989-214bb080-9521-11eb-9b41-9aea132a7f96.png)

I don't seem to have an option "Display on home screen" like you do.
I'm on linuxserver/jellyfin:latest, right now that'd be `Version: 10.7.1`

Thanks

**Comment by tuyennn** [comment]
Bump 
using docker linuxserver/jellyfin:latest only `Display in home screen sections such as 'Latest Media' and 'Continue Watching'` is available
